log:
  level: INFO

entryPoints:
  web:
    address: ':80'
  flower:
    address: ':5555'

http:
  routers:
    web-secure-router:
      rule: 'Host(`youbrajrai.com.np`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    flower-secure-router:
      rule: 'Host(`youbrajrai.com.np`)'
      entryPoints:
        - flower
      service: flower

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:8000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
